### ISSUE TITLE
Add html section to website for development of informed consumer feature

### ISSUE THREAD

**Issue by mcpat1** [PiratesDen/Potp#1]
Add section within index.html to website for development of informed consumer feature.  

The thought is to take automatic1.html or automatic2.html and duplicate it between those sections.

**Comment by jnelson9993** [comment]
Added the INFORMED section to the index page. The section is based off of automatic1.html, but that can be fixed with relative ease if need be. I just added a checkbox, which just acts like the Start button if you click it. I just wanted to give some kind of .html skeleton for the INFORMED section.
