### ISSUE TITLE
KUNGFU-1

### ISSUE THREAD

**Issue by Unit720** [PiratesDen/Potp#2]
Implement KUNGFU

Add html section to index.html to describe functionality and outline implementation.
Add mini_kungfu.html to demonstrate mechanics introduced through this functionality.
Add some file (automatic_kungfu.html?) to demonstrate sandbox featuring this functionality.

**Comment by PiratesDen** [comment]
Did not implement mini_kingfu.html.  Contacted Unit720 to gather additional information about the mini
