### ISSUE TITLE
Implement check of the neighbors happiness before completing move

### ISSUE THREAD

**Issue by PiratesDen** [PiratesDen/Potp#4]
When implementing this issue, identify the controlling structure or condition that initiates the movement of the polygon.  The team has decided a module should be implemented that gets called within the loop. 

Reference lines 430 to 448 in automatic.js

**Comment by jnelson9993** [comment]
The application only moves the sad polygons, and they cannot be any more sad no matter where they move. Therefore, it's impossible for them to make an uninformed move because no move will make a sad polygon more sad. This means no modifications are required to add the INFORMED feature.
