### ISSUE TITLE
Implement data structure that stores the segregation difference between each move

### ISSUE THREAD

**Issue by PiratesDen** [PiratesDen/Potp#8]
Implement data structure that stores the segregation difference between each move as a metric for correctness.

The data structure must adhere to the following parameters:
(1) each move must exist on a separate line
(2) each line must have
    (a) the segregation difference in the first column 
    (b) the string "threshold hit" if segregation difference is >= threshold; o.w. the empty string

**Comment by jnelson9993** [comment]
Implemented the data structure, but instead of having the difference be in the first column, I separated the segregation values per move into their own separate columns.
